version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy: 
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - run:
          name: deploy-gh-pages
          command: chmod +x ./scripts/build.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
